### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/brand#1]
## `@todo`
* [ ] add official play colors
* [ ] add official play font(s)
* [ ] add official play logo from [`brand#3` new play logo](https://github.com/playproject-io/brand/issues/3)
* [ ] add official play project logos
* [ ] add brand book demo page
* [ ] [`brand#2` Ideas of interaction design collection](https://github.com/playproject-io/brand/issues/2)
---

**Comment by ninabreznik** [comment]
When I think of Play project, I think of a project that is focusing on people and different projects working together: 
- hypermodular, 
- p2p, 
- no hierarchies, 
- self organized,
- transparent 

It's about building tooling for this.
