### ISSUE TITLE
Ideas of interaction design collection

### ISSUE THREAD

**Issue by fionataeyang** [playproject-io/brand#2]
## `@todo`
* [x] make concept for landing page
* [x] make mood boards for play brand
* [x] design landing page for play project
* [x] implement landing page and make and publish all brand assets
* [ ] clean up this issue
* [ ] write text for landing page and consider asking a native speaker to proof read it

---
On Google drive
[Design sources](https://drive.google.com/drive/u/0/folders/16-hym0eQ1ns93yUo5W-u2ozvo5sorbIN)

## Ideas on Pinterest
1. [css web](https://pin.it/bncad2e7wi3dpa)
2. [geometric abstraction](https://pin.it/wupks5bc5k3pxt)

## CSS animation
1. https://css-tricks.com/css-animation-libraries/
3. https://wowjs.uk/
4. https://animejs.com/
5. https://dixonandmoe.com/rellax/
6. https://scroll-out.github.io/
7. wave effect https://codepen.io/tedmcdo/pen/PqxKXg
8. text animation http://cssanimation.io/getting-started.html

* Will be applying rellax + scroll-out + animejs

## Page transition demo
https://codepen.io/mburakerman/pen/roJmaZ
https://codepen.io/firestar300/pen/zLKZVZ
https://codepen.io/ktsn/pen/wrxymV
https://codepen.io/marcelo-ribeiro/pen/xOOKpO

##  others
Resize Header on Scroll
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_shrink_header_scroll
https://codepen.io/osublake/pen/NdEONL

Transitions Only After Page Load
https://css-tricks.com/transitions-only-after-page-load/

Card hover effects
https://tympanus.net/Development/HoverEffectIdeas/

Css effects tutorial and reference
https://tympanus.net/codrops/

photo effect
https://tympanus.net/Tutorials/MotionHoverEffects/index3.html
https://tympanus.net/Development/FlowmapDeformation/index2.html

mouse trails effect
https://tympanus.net/codrops/2019/09/24/crafting-stylised-mouse-trails-with-ogl/

## plugin
https://github.com/oframe/ogl

svg animation
https://github.com/maxwellito/vivus

In-view 
when scrolling down to element will be running the event.
https://github.com/camwiegert/in-view
https://pudding.cool/process/how-to-implement-scrollytelling/#inview

**Comment by serapath** [comment]
checked then all.
* the `plugin`, `others`, `page transition demos`, `css animation` look great once we know design concept for our page.
* i checked all the `ideas on pinterest` and added some of them to: https://www.pinterest.de/serapath/play3/
  * in the past we started with https://www.pinterest.de/serapath/play/
  * and then came https://www.pinterest.de/serapath/play2/

**other inspiration**
* https://monolith.xyz/

**guiding themes**
* [`moebius`](https://www.google.com/search?q=moebius&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjYmMLDi8TmAhVEIbcAHVW5DdMQ_AUoAXoECBMQAw&biw=1707&bih=818&dpr=2.25) who made "sci-fi" which is full of technology but also merged that with celebrating nature - but the problem is that it still has a conflict and/or post war feel to it
* then we have [`solarpunk`](https://www.google.com/search?q=solarpunk&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjcmNbui8TmAhWNXisKHSIOAMUQ_AUoAXoECBUQAw&biw=1707&bih=818) but the problem is, that even though there is a lot of nature, the buildings are sky-scraper like and kind of "megalomaniac" structures. It does not feel minimal and modular where people could actually feel they could make it themselves ... and it's almost exclusively about architecture. If it had more [`tinyhouse`](https://www.google.com/search?q=tinyhouse&source=lnms&tbm=isch&sa=X&ved=2ahUKEwibkoCNjcTmAhXaV30KHV62CngQ_AUoAXoECBEQAw&biw=1707&bih=818) aspect to it, it would be still architecture, but at least it's more graspable how people can do this themselves :-)
* then we have [`synthwave`](https://www.pinterest.de/search/pins/?q=synthwave&rs=typed&term_meta[]=synthwave%7Ctyped) which is contemporary, but it mostly about city, fast cars - basically celebrating white male privilege from the 80s and is not concerned with gender balance or inclusion or openeness and especially climate change at all
* but we have the digital almost counter version of it [`seapunk`](https://www.pinterest.de/search/pins/?q=seapunk&rs=typed&term_meta[]=seapunk%7Ctyped) which is very much putting animals/plans/natural landscapes/etc... at the center stage and where colors are very much in support of queer. Still it might have a touch of irony/parody to it ..so it's hard to make it look professional, but just having that style in very high quality maybe makes it possible? :-)

**So our, or at least my thoughts are:**
* how to make solar punk more modular and real and not just architecture?
* how to to make seapunk so awesome, that - even though its very different - people still see the professionalism
* or generally how to express the values that we want to communicate in our website design

The first time around - when we did `smartcontract.codes`, we started with "mood boards" and stuff, to slowly get closer to the kind of style we want to use to communicate and maybe we should try that again, even if it will cost us a lot of time and we would need to iterate a lot

**Comment by fionataeyang** [comment]
Demo concept for landing page
These are the design concept for the landing page, the idea can make or change.

Header
![playproject_landing_page_header](https://user-images.githubusercontent.com/9526525/71361126-fa3bca80-25cc-11ea-9c7f-9dfe2a3c4aad.jpg)

Header1
![playproject_landing_page_header1](https://user-images.githubusercontent.com/9526525/71361225-4ab32800-25cd-11ea-9b37-b629d0d04b57.jpg)

Smart Contract codes
![playproject_landing_smartcontract codes](https://user-images.githubusercontent.com/9526525/71361129-fad46100-25cc-11ea-97eb-708ed8c5b054.jpg)

Smart Contract UI
![playproject_landing_page_smartcontract ui](https://user-images.githubusercontent.com/9526525/71361127-fad46100-25cc-11ea-8e2e-8e0a2e4333be.jpg)

**Comment by serapath** [comment]
very nice. i love this iteration. i talked with nina too and we were thinking:
1. maybe we could iterate on the "Smart Contract UI" font
2. maybe try without or an alternative to the unicorn
3. use the first header and try different birds to match the low poly style

everything else (clouds, trees, etc..., colors, ...) are amazing to me :-)

**our goals are to not make it look `depressive` nor `agressive` nor `sad` nor `dystopian` nor any other kind of `bad vibe`.

* we want to support things associated with `"feminism"`, `"climate change"`, `"gender balance"`, `"playfulness"`, etc... to collect a `positive vibe` AND to connect that to `"future"`, `"technology"`, `"scifi"`, etc... because even though we try to support the values and goals, often they are not much connected to technology, but we are all about technology, so yeah - it's not easy.

**Comment by fionataeyang** [comment]
![header_scene](https://user-images.githubusercontent.com/9526525/71663941-14766500-2d92-11ea-9df0-318c4f4c8a77.jpg)

![header_scene1](https://user-images.githubusercontent.com/9526525/71663943-150efb80-2d92-11ea-9d32-9852962cf869.png)
![section_scene1](https://user-images.githubusercontent.com/9526525/71663948-15a79200-2d92-11ea-9e4a-195c5940bca2.png)

![header_scene1-1](https://user-images.githubusercontent.com/9526525/71663942-150efb80-2d92-11ea-8245-6a307bfa44b2.png)
![section_scene1-2](https://user-images.githubusercontent.com/9526525/71663947-15a79200-2d92-11ea-8d8a-51ff5fbdb448.png)

![header_scene2](https://user-images.githubusercontent.com/9526525/71663945-150efb80-2d92-11ea-8112-b3f9eb13a1bb.png)
![section_scene2](https://user-images.githubusercontent.com/9526525/71663949-16402880-2d92-11ea-8784-f03fd8089352.png)

![header_scene3](https://user-images.githubusercontent.com/9526525/71663946-15a79200-2d92-11ea-8161-85b5f1d3b5d3.png)
![section_scene3](https://user-images.githubusercontent.com/9526525/71663950-16402880-2d92-11ea-9017-e25ae5c0fa6e.png)

**Comment by serapath** [comment]
Alright - maybe we can use all of the above ideas and combine them into **"floating islands"**
* see https://pinterest.com/serapath/play4

The good thing is, that this gives us a lot of modularity and flexibility, because we can change the background: `in space`, `under water`, `night sky`, `gradient/fantasy?/rainbow?` ... or any combination
and each island can have a different topic and/or color scheme. It is easy to switch the background or an island for some other island without the need to create an entire new page.
Usually when you change a significant chunk of a landing page, maybe the whole page concept does not make sense anymore, but with the island, individual parts become more independent :-)

**Comment by fionataeyang** [comment]
Updated Jan. 7 2019
![landing page1](https://user-images.githubusercontent.com/9526525/71890646-b70e5980-317f-11ea-9c1e-ad8321bd02a9.png)

**Comment by serapath** [comment]
For completeness and archival reasons:
![play landingpage draft1](https://files.gitter.im/playproject-io/community/p51b/play_landing_web.png)
![play landingpage draft1 mobile](https://files.gitter.im/playproject-io/community/p51b/play_landing_mobile.png)

**Comment by serapath** [comment]
for completeness and archival reasons:
![play landingpage draft2a](https://files.gitter.im/playproject-io/community/NB4F/play_landing_web_template2.jpg)
![play landingpage draft2b](https://files.gitter.im/playproject-io/community/NB4F/play_landing_web_template1.jpg)

**Comment by serapath** [comment]
**elements to be used on the page**
* [low poly trees](https://www.pinterest.de/pin/324470348136767035/)
* [low poly nature](https://www.pinterest.de/search/pins/?q=polygonal%20nature&rs=typed&term_meta[]=polygonal%7Ctyped&term_meta[]=nature%7Ctyped)
* [low poly nature2](https://www.pinterest.de/search/pins/?q=low%20poly%20nature&rs=typed&term_meta[]=low%7Ctyped&term_meta[]=poly%7Ctyped&term_meta[]=nature%7Ctyped)
* [low poly world](https://i.pinimg.com/originals/a4/87/e5/a487e5825e62b69634706a5942384560.jpg)
* [low poly world2](https://mos-inform.com/wp-content/uploads/2019/04/f9f7121e310aecef972d59d3f5737347.jpg)

**Comment by fionataeyang** [comment]
Updated 1.14.2020
![landing-page2](https://user-images.githubusercontent.com/9526525/72339006-8c348000-3700-11ea-98cd-630e4fd1fe06.png)

**Comment by fionataeyang** [comment]
Updated: 1.29.2020
![landing-page3](https://user-images.githubusercontent.com/9526525/73328520-11896a00-4295-11ea-98e7-87d78b99799b.png)

**Comment by fionataeyang** [comment]
updated: 1.31.2020
![landing-page4](https://user-images.githubusercontent.com/9526525/73470692-3d0a7280-43c3-11ea-833c-61d89e165757.png)

**Comment by fionataeyang** [comment]
Update: 2.12.2020

For Tablet
![playproject_tablet](https://user-images.githubusercontent.com/9526525/74304500-25a29080-4d98-11ea-9c9c-0ae4bba710b1.jpg)

For PC
![landing-page4](https://user-images.githubusercontent.com/9526525/74304686-ba0cf300-4d98-11ea-9606-4750d84dcf0f.jpg)

**Comment by fionataeyang** [comment]
[2.19.20 Play meeting note](https://github.com/playproject-io/datdot/issues/30)

### put all assets for Playproject to BRAND repo

- Assets
- Landing page
- Logo
- Stickers
- in the landing page repo
- Assets (all landing page assets here)

### Logo:
try how it will look in black & white version too

### Header title
Search some ideas from the website

**Comment by fionataeyang** [comment]
updated: 2.28.20 
# Footer redesign
### Footer demo1
![footer-template1](https://user-images.githubusercontent.com/9526525/75564627-70562500-5a87-11ea-9b0e-1e95bfb411f4.png)

### Footer demo2
![footer-demo2](https://user-images.githubusercontent.com/9526525/75563532-76e39d00-5a85-11ea-9a2a-3d30f69ccdc4.png)

### Footer demo3
![footer-template3](https://user-images.githubusercontent.com/9526525/75563808-ed809a80-5a85-11ea-991d-453fa60b99bf.png)

**Comment by fionataeyang** [comment]
# The design of twitter profile
### Banner1
![banner1](https://user-images.githubusercontent.com/9526525/75846798-5f573c00-5e18-11ea-80a9-b26a44b360e7.jpg)

### Banner2
![banner2](https://user-images.githubusercontent.com/9526525/75846806-62eac300-5e18-11ea-8c6f-cbba6557ae00.jpg)

### Banner3
![banner3](https://user-images.githubusercontent.com/9526525/75846810-641bf000-5e18-11ea-92eb-7e1c7b4588a1.jpg)

### Banner4
![banner4](https://user-images.githubusercontent.com/9526525/75846942-b230f380-5e18-11ea-98f8-86cac3539111.jpg)

## Demos
![twitter-post-demo](https://user-images.githubusercontent.com/9526525/75847205-7f3b2f80-5e19-11ea-8fc2-2b068f6c6b7e.jpg)
![twitter-profile-demo](https://user-images.githubusercontent.com/9526525/75847211-83ffe380-5e19-11ea-9d46-0f6c8a1e7e49.jpg)

**Comment by fionataeyang** [comment]
# Twitter profile
### Banner
![twitter-banner2](https://user-images.githubusercontent.com/9526525/76187427-467fc980-6210-11ea-9a12-725928738757.jpg)

### Avatar
Avatar1
![avatar](https://user-images.githubusercontent.com/9526525/76187442-539cb880-6210-11ea-9471-adf199a8134b.png)
Avatar2
![avatar1](https://user-images.githubusercontent.com/9526525/76187695-f9502780-6210-11ea-92b5-86c64cafc1ec.png)
Avatar3
![avatar2](https://user-images.githubusercontent.com/9526525/76187699-fb19eb00-6210-11ea-9923-d394b705bdee.png)
Avatar4
![avatar3](https://user-images.githubusercontent.com/9526525/76188121-3ff25180-6212-11ea-925f-e2416a6d6b0c.png)
Avatar5
![avatar4](https://user-images.githubusercontent.com/9526525/76188125-41bc1500-6212-11ea-8c3a-5b5de145d967.png)
Avatar6
![avatar5](https://user-images.githubusercontent.com/9526525/76188128-42ed4200-6212-11ea-9b22-469af44b209b.png)
Avatar7 (white)
![avatar6](https://user-images.githubusercontent.com/9526525/76188131-454f9c00-6212-11ea-88d8-346334fb1e12.png)
Avatar8
![avatar7](https://user-images.githubusercontent.com/9526525/76189082-b7c17b80-6214-11ea-8467-50c4835611f5.png)
Avatar9
![avatar8](https://user-images.githubusercontent.com/9526525/76189086-b8f2a880-6214-11ea-9e8b-ed5430a79d47.png)
Avatar10
![avatar9](https://user-images.githubusercontent.com/9526525/76189094-bc862f80-6214-11ea-92b4-b9020b22eee7.png)

Avatar transparent background
![avatar-transparent](https://user-images.githubusercontent.com/9526525/76188153-57c9d580-6212-11ea-8144-20567d0139ed.png)
