### ISSUE TITLE
new play logo

### ISSUE THREAD

**Issue by serapath** [playproject-io/brand#3]
## `@todo`
* [x] define new play logo
* [x] decide for logo
* [ ] put all related asset on github
* [x] add logo and favicon and maybe other versions to github brand repo
* [x] use logo and favicon on landing page

---

**play background patterns:**
* [hirnoymus bosch](https://www.google.com/search?biw=1707&bih=818&tbm=isch&sa=1&ei=n132XZHtO-qT4-EPxouZmAs&q=hirnoymus+bosch&oq=hirnoymus+bosch&gs_l=img.3...14267.18061..18178...3.0..0.122.1736.13j6......0....1..gws-wiz-img.......0i67j0j0i131j0i10j0i30j0i5i30j0i24j0i10i24.UbfEof_RLFA&ved=0ahUKEwjRuOnwh7jmAhXqyTgGHcZFBrMQ4dUDCAc&uact=5)
* [moebius](https://www.google.com/search?biw=1707&bih=818&tbm=isch&sa=1&ei=jV32XbXPNLmQ4-EPwIumuAE&q=moebius&oq=moebius&gs_l=img.3..0l10.16608.17231..17343...0.0..0.85.697.9......0....1..gws-wiz-img.......0i131.m-TGrjixwxw&ved=0ahUKEwj1yZfoh7jmAhU5yDgGHcCFCRcQ4dUDCAc&uact=5)
* [dickbutt](https://www.google.com/search?q=find+dickbutt&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjlhovnh7jmAhVZcCsKHfqWC1kQ_AUoAXoECAsQAw&biw=1707&bih=818&dpr=2.25)

**inspiration**
* [play logo codepen](https://codepen.io/ninabreznik/pen/LYEZeLR)
* [pattern1](http://world.std.com/~wij/index.html)
* [voxels](https://www.google.com/search?biw=1707&bih=818&tbm=isch&sa=1&ei=BkP2XdOpIOif4-EP_8Kp6A0&q=voxel+3d&oq=voxel+3d&gs_l=img.3..0l4j0i5i30j0i8i30l3j0i30j0i24.10369.11316..11439...0.0..0.90.808.10......0....1..gws-wiz-img.......0i67.HNG2xGEMuUc&ved=0ahUKEwjTxOnB7rfmAhXozzgGHX9hCt0Q4dUDCAc&uact=5)
* [pixels](https://www.google.com/search?q=pixel+2d&sxsrf=ACYBGNQ3fKAGmIwAoxVm8folv9U0HSSyUw:1576420080527&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjdmKq37rfmAhWM7GEKHQw8Cb0Q_AUoAXoECAwQAw&biw=1017&bih=916)
* [usable as identicons](http://identicons.pepe.asia/)
* [2d/3d voxel patterns](http://world.std.com/~wij/color/index-animated.html)
* [play font logo?](https://twitter.com/tchoi8/status/1205488427120177154)
* **[lovely hexagon background pattern in music video](https://www.youtube.com/watch?v=v72KhB8iZ-0)**
* [inspiration1](https://www.flickr.com/photos/tiago_hands/48444523757/)
* [inspiration2](https://www.deviantart.com/skyjohn/art/Hexagon-Color-Chart-264015314)
* **[inspiration3](https://drive.google.com/file/d/1HDx-Jufkbe8D6Z2xcRKyYGVUkMOG4Efy/view)**
* [inspiration4](https://www.uidownload.com/free-vectors/colection-of-3d-cubes-492255)
* [inspiration5](https://www.etsy.com/sg-en/listing/541264597/even-planner-polygonal-logo-design)
* [inspiration6](https://www.etsy.com/sg-en/listing/527465136/makeup-artist-logo-rose-gold-textured?ref=landingpage_similar_listing_top-2)
* [inspiration7](http://www.pkclsoft.com/wp/tag/game/)
* [inspiration8](https://favpng.com/png_view/shape-hexagon-polygon-geometry-shape-png/kZsdWuYB)

**tutorial to code logo**
* [hexagon tutorial1](https://gamedevelopment.tutsplus.com/tutorials/creating-hexagonal-minesweeper--cms-28655)
* [hexagon tutorial2](https://www.redblobgames.com/grids/hexagons/)
* [hexagon tutorial3](https://jsfiddle.net/juwalbose/b4aavdxg/?utm_source=website&utm_medium=embed&utm_campaign=b4aavdxg)
* [hexagon tutorial4](https://jsfiddle.net/zufxLjg2/)

**Comment by fionataeyang** [comment]
![logo1-1](https://user-images.githubusercontent.com/9526525/74305689-96977780-4d9b-11ea-9165-ed11c67dab2f.png)
![logo1-2](https://user-images.githubusercontent.com/9526525/74305695-98f9d180-4d9b-11ea-8624-6ab87c50d23d.png)
![logo1-3](https://user-images.githubusercontent.com/9526525/74305697-99926800-4d9b-11ea-8d7d-80357bb51fcb.png)
![logo1-4](https://user-images.githubusercontent.com/9526525/74305699-9a2afe80-4d9b-11ea-9acf-fcfba1638c8a.png)
![logo1-6](https://user-images.githubusercontent.com/9526525/74305700-9ac39500-4d9b-11ea-8edd-318c5cfe0f1a.png)
![logo1-7](https://user-images.githubusercontent.com/9526525/74305701-9ac39500-4d9b-11ea-91cd-640c245e72f5.png)
![logo1-8](https://user-images.githubusercontent.com/9526525/74305702-9b5c2b80-4d9b-11ea-9951-96c2c6d6e4b9.png)
![logo2-1](https://user-images.githubusercontent.com/9526525/74305703-9b5c2b80-4d9b-11ea-9e3d-0b2fd53a872b.png)
![logo2-2](https://user-images.githubusercontent.com/9526525/74305704-9bf4c200-4d9b-11ea-8e32-ff1316de85f5.png)
![logo2-3](https://user-images.githubusercontent.com/9526525/74305705-9c8d5880-4d9b-11ea-8644-bbe8d7c49f21.png)
![logo2-4](https://user-images.githubusercontent.com/9526525/74305706-9c8d5880-4d9b-11ea-8a5a-b2447d7f0314.png)
![logo2-5_1](https://user-images.githubusercontent.com/9526525/74305707-9d25ef00-4d9b-11ea-99b7-95a219ae4ea9.png)
![logo2-5](https://user-images.githubusercontent.com/9526525/74305709-9dbe8580-4d9b-11ea-938b-1134a0d9d7b7.png)
![logo2-6](https://user-images.githubusercontent.com/9526525/74305711-9e571c00-4d9b-11ea-8b3a-fa83b7f490a0.png)
![logo2-7](https://user-images.githubusercontent.com/9526525/74305712-9eefb280-4d9b-11ea-98b0-5010d5298ac8.png)
![logo2-8](https://user-images.githubusercontent.com/9526525/74305714-9eefb280-4d9b-11ea-9c62-881c2f7b1471.png)
![logo3-1](https://user-images.githubusercontent.com/9526525/74305716-9f884900-4d9b-11ea-8b42-a4d0016bb2b3.png)
![logo3-2](https://user-images.githubusercontent.com/9526525/74305717-a020df80-4d9b-11ea-9296-9e178823e65a.png)
![logo3-3](https://user-images.githubusercontent.com/9526525/74305718-a020df80-4d9b-11ea-99ba-2652fc3b492d.png)
![logo3-4](https://user-images.githubusercontent.com/9526525/74305719-a0b97600-4d9b-11ea-873b-e898879611b9.png)
![logo3-5](https://user-images.githubusercontent.com/9526525/74305720-a1520c80-4d9b-11ea-9779-da7f736c9aa3.png)
![logo3-6](https://user-images.githubusercontent.com/9526525/74305723-a1520c80-4d9b-11ea-8f4d-09028208598c.png)
![logo3-7](https://user-images.githubusercontent.com/9526525/74305724-a1eaa300-4d9b-11ea-8191-235f78531ad9.png)
![logo3-8](https://user-images.githubusercontent.com/9526525/74305725-a1eaa300-4d9b-11ea-861b-d7c989310203.png)
